server:
  port: 9595
  servlet:
    context-path: /kafka
spring:
  application:
    name: spring-kafka-broker
  kafka:
    producer:
      bootstrap-servers: localhost:19092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer